services:
  ittools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.ittools.tls: true
      traefik.http.routers.ittools.entrypoints: https
      traefik.http.routers.ittools.rule: Host(`tools.intern.local`)
      traefik.http.routers.ittools.service: ittools
      traefik.http.services.ittools.loadbalancer.server.port: 80
    networks:
      - proxy
networks:
  proxy:
    external: true