version: '3.3'
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    volumes:
      - ./data/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ./data/extraConfigs:/configs
      - ./data/customFiles:/customFiles/
      - ./data/logs:/logs/
      - ./data/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=de_DE
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.stirling-pdf.tls: true
      traefik.http.routers.stirling-pdf.entrypoints: https
      traefik.http.routers.stirling-pdf.rule: Host(`pdf.intern.local`)
      traefik.http.routers.stirling-pdf.service: stirling-pdf
      traefik.http.services.stirling-pdf.loadbalancer.server.port: 8080
    networks:
      - proxy
networks:
  proxy:
    external: true
